// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.1
// source: gravatar.proto

package gravatar

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GravatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Size  int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GravatarRequest) Reset() {
	*x = GravatarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravatar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GravatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GravatarRequest) ProtoMessage() {}

func (x *GravatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gravatar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GravatarRequest.ProtoReflect.Descriptor instead.
func (*GravatarRequest) Descriptor() ([]byte, []int) {
	return file_gravatar_proto_rawDescGZIP(), []int{0}
}

func (x *GravatarRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GravatarRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GravatarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GravatarResponse) Reset() {
	*x = GravatarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravatar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GravatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GravatarResponse) ProtoMessage() {}

func (x *GravatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gravatar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GravatarResponse.ProtoReflect.Descriptor instead.
func (*GravatarResponse) Descriptor() ([]byte, []int) {
	return file_gravatar_proto_rawDescGZIP(), []int{1}
}

func (x *GravatarResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_gravatar_proto protoreflect.FileDescriptor

var file_gravatar_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x72,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x56, 0x0a,
	0x0f, 0x47, 0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x67,
	0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x2e, 0x47, 0x72, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gravatar_proto_rawDescOnce sync.Once
	file_gravatar_proto_rawDescData = file_gravatar_proto_rawDesc
)

func file_gravatar_proto_rawDescGZIP() []byte {
	file_gravatar_proto_rawDescOnce.Do(func() {
		file_gravatar_proto_rawDescData = protoimpl.X.CompressGZIP(file_gravatar_proto_rawDescData)
	})
	return file_gravatar_proto_rawDescData
}

var file_gravatar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gravatar_proto_goTypes = []interface{}{
	(*GravatarRequest)(nil),  // 0: gravatar.GravatarRequest
	(*GravatarResponse)(nil), // 1: gravatar.GravatarResponse
}
var file_gravatar_proto_depIdxs = []int32{
	0, // 0: gravatar.GravatarService.Generate:input_type -> gravatar.GravatarRequest
	1, // 1: gravatar.GravatarService.Generate:output_type -> gravatar.GravatarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gravatar_proto_init() }
func file_gravatar_proto_init() {
	if File_gravatar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gravatar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GravatarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravatar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GravatarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gravatar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gravatar_proto_goTypes,
		DependencyIndexes: file_gravatar_proto_depIdxs,
		MessageInfos:      file_gravatar_proto_msgTypes,
	}.Build()
	File_gravatar_proto = out.File
	file_gravatar_proto_rawDesc = nil
	file_gravatar_proto_goTypes = nil
	file_gravatar_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GravatarServiceClient is the client API for GravatarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GravatarServiceClient interface {
	Generate(ctx context.Context, in *GravatarRequest, opts ...grpc.CallOption) (*GravatarResponse, error)
}

type gravatarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGravatarServiceClient(cc grpc.ClientConnInterface) GravatarServiceClient {
	return &gravatarServiceClient{cc}
}

func (c *gravatarServiceClient) Generate(ctx context.Context, in *GravatarRequest, opts ...grpc.CallOption) (*GravatarResponse, error) {
	out := new(GravatarResponse)
	err := c.cc.Invoke(ctx, "/gravatar.GravatarService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GravatarServiceServer is the server API for GravatarService service.
type GravatarServiceServer interface {
	Generate(context.Context, *GravatarRequest) (*GravatarResponse, error)
}

// UnimplementedGravatarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGravatarServiceServer struct {
}

func (*UnimplementedGravatarServiceServer) Generate(context.Context, *GravatarRequest) (*GravatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}

func RegisterGravatarServiceServer(s *grpc.Server, srv GravatarServiceServer) {
	s.RegisterService(&_GravatarService_serviceDesc, srv)
}

func _GravatarService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GravatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravatarServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravatar.GravatarService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravatarServiceServer).Generate(ctx, req.(*GravatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GravatarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravatar.GravatarService",
	HandlerType: (*GravatarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _GravatarService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gravatar.proto",
}
